workdir: test

# Setting for SV analysis
# gff always relative to the workdir

gffinput: assembly/bos_annot.gff.gz

# Setting for rna-seq analysis
rna_seq: False
reference: UCDsm
# diamond protein db for blast 
refprot: /ref/to/diamondprotdb
rna_basedir: /ref/to/fastq_rna

# setting for wgs analysis
dna_seq: False
dna_basedir: /ref/to/bamfile
dna_ref: 
 - ref1
 - ref2
 - ref3
dna_anims:
 - anim1
 - anim2
 - anim3
 - anim4
 - anim5

