name: pangenome_test
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>3.7.1
  - r-base==3.5.1
  - snakemake==5.30.1
  - pybedtools
  - pypdf2==1.26.0
  - markdown==3.0.1
  - r-ape
  - r-optparse
  - r-tidyverse
  - mash
  - python-graphviz
  - weasyprint 
