workdir: final_graph

# Setting for SV analysis
# gff always relative to the workdir

gffinput: input.gff

# Setting for rna-seq analysis
rna_seq: False
reference: ARS
# diamond protein db for blast 
refprot: diamondprotdb
rna_basedir: fastq_rna

# setting for wgs analysis
dna_seq: False
dna_basedir: file.bam
dna_ref: 
 - ref1
 - ref2
dna_anims:
 - anim1
 - anim2
