name: snakemaker
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Graphviz
        run: sudo apt install graphviz
      - name : Install snakemake
        uses: BSFishy/pip-action@v1
        with:
          packages: |
                  snakemake==5.30.1
                  pandas
      #- name: snakemake
        #uses: snakemake/snakemake-github-action@v1.11.0
        #with:
          #directory: 'test'
          #args: '--snakefile snake_graph.py --dryrun --rulegraph | dot -Tpdf -orulegraph.pdf'
      - name: Run snakemake pipeline
        run: snakemake -j 1 --configfile config/config.yaml --dryrun --rulegraph -s snake_graph.py | dot -Tpdf -orulegraph.pdf
      - name: Obtain pipeline graph
        uses: actions/upload-artifact@v2
        with:
          name: rulegraph
          path: rulegraph.pdf
