name: snakemaker
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: snakemake
        uses: snakemake/snakemake-github-action@v1.11.0
        with:
          directory: 'test'
          args: '--snakefile snake_graph.py --dryrun'
